# Generated by Django 3.2.20 on 2023-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPRESA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.IntegerField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
    ]
